db:
  daystatsfile:
    path: '/data/asstats/asstats/asstats_day.txt'

topinterval:
  month:
    hours: '720' # 30x24h
    statsfile: '/data/asstats/asstats/asstats_month.txt'
    label: '30 days'

config:
  knownlinksfile: '/data/asstats/conf/knownlinks'
  asinfofile: 'ressources/asinfo.txt'

customlinks:
  PeeringDB: 'https://www.peeringdb.com/asn/%as%'
  robtex: 'https://www.robtex.com/as/as%as%.html'
  HE: 'http://bgp.he.net/AS%as%'
  RIPEstat: 'https://stat.ripe.net/AS%as%#tabId=at-a-glance'
  CIDR v4: 'http://www.cidr-report.org/cgi-bin/as-report?as=AS%as%&view=2.0'
  CIDR v6: 'http://www.cidr-report.org/cgi-bin/as-report?as=AS%as%&view=2.0&v=6'
  Radar Qrator: 'https://radar.qrator.net/as%as%/'
