application:
  routes_file: 'app/config/routes.yml'
  asstats_file: 'app/config/as-stats.yml'
  release: '1.0'
  controller: 'src/Controllers'
  model: 'src/Models'
  locale: 'fr'
  debug: TRUE
  template_dir: 'web/template'
  twig:
    enable_cache: FALSE
    path: 'src/Views'
    timezone: 'Europe/Paris'
